apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      name: my-web-app
      labels:
        app: db 
    spec:
      containers:
        - name: my-nginx-app   
          image: esraa123/os-img
          imagePullPolicy: IfNotPresent
          