apiVersion: v1
kind: Pod
metadata:
  name: my-web-app
  labels:
    app: db
spec:
  containers:
    - name: my-nginx-app
      image: esraa123/os-img
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80